# 1. Information about the model to be fine-tuned
model_to_finetune:
  path_to_metadata: '../saved_models/model_20251001_150357_metadata.yaml'

# 2. Data configuration for fine-tuning
data:
  base_path: '../../../data/datasets/cnn_rnn/1'
  train_file: train.csv
  val_file: val.csv
  state_for_finetuning: 'PUNJAB'

# 3. Training configuration for fine-tuning
training:
  n_epochs: 50
  early_stopping_patience: 10
  validation_loss: 'l1'

# 4. Dataloader configuration
dataloader:
  num_workers: 0
  pin_memory: false
  persistent_workers: false
  prefetch_factor: null
  drop_last_train: true

# 5. HPO configuration
optimization:
  study_name: 'punjab_1'
  hpo_dir: '../../../experiments/hpo/fine_tuning'
  n_trials: 10
  timeout_hours: 1
  pruning: false

  # 6. Hyperparameter search space for fine-tuning
  hparam_search_space:
    rnn_dropout_prob:
      type: 'float'
      low: 0.1
      high: 0.5

    fc_dropout_prob:
      type: 'float'
      low: 0.1
      high: 0.6

    learning_rate:
      type: 'loguniform'
      low: 1e-8
      high: 1e-5

    weight_decay:
      type: 'loguniform'
      low: 1e-7
      high: 1e-3
    
    huber_delta:
      type: 'float'
      low: 1.0
      high: 1500.0

    batch_size:
      type: 'categorical'
      choices: [16, 32, 64]
